services:
    frontend:
        build:
            context: frontend/docker
            dockerfile: development/nginx/Dockerfile
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`morephoto.loc`) || Host(`www.morephoto.loc`)
            - traefik.http.routers.frontend.entryPoints=https
            - traefik.http.routers.frontend.tls=true
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www\.morephoto\.loc/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}morephoto.loc/$${2}
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    frontend-node:
        build:
            context: frontend/docker
            dockerfile: development/node/Dockerfile
        environment:
            NODE_ENV: development
            VITE_API_BASE_URL: https://api.morephoto.loc
            HOST: 0.0.0.0 # Важно для Vite!
        command: sh -c "npm run dev" # Явное указание хоста
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"  # Проброс порта Vite
        tty: true

    frontend-node-cli:
        build:
            context: frontend/docker
            dockerfile: development/node/Dockerfile
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.morephoto.rule=Host(`api.morephoto.loc`) || Host(`www.api.morephoto.loc`)
            - traefik.http.routers.morephoto.entryPoints=https
            - traefik.http.routers.morephoto.tls=true
            - traefik.http.services.morephoto.loadBalancer.server.port=80
            - traefik.http.middlewares.morephoto-redirect.redirectRegex.permanent=true
            - traefik.http.middlewares.morephoto-redirect.redirectRegex.regex=^(https?://)www\.api.morephoto\.loc/(.*)$$
            - traefik.http.middlewares.morephoto-redirect.redirectRegex.replacement=$${1}api.morephoto.loc/$${2}
            - traefik.http.routers.morephoto.middlewares=morephoto-redirect

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:  # Добавьте это!
            - "3307:3307"
            #- "9003:9003"  # Добавьте эту строку
        volumes:
            - ./api:/app
        environment:
            APP_DEBUG: 1
            REDIS_HOST: redis
            REDIS_PORT: 6379
            PHP_IDE_CONFIG: "serverName=API"

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./api:/app
        environment:
            APP_DEBUG: 1

    api-mysql:
        build:
            context: api/docker
            dockerfile: development/mysql/Dockerfile
        restart: always
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secrets
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - api-mysql:/var/lib/mysql
        ports:
            - "33069:3306"

    api-memcached:
        image: memcached:latest
        restart: always
        command: memcached -m 64m -vv
        ports:
            - "11211:11211"
        networks:
            - default

volumes:
    api-mysql:

networks:
    traefik-public:
        external: true
        driver: bridge
