services:
    frontend:
        image: ${REGISTRY}/rebit-p2p-frontend:${IMAGE_TAG}
        environment:
            VITE_API_URL: https://api.rebit-pro.ru
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.frontend.rule=Host(`app.rebit-pro.ru`) || Host(`www.app.rebit-pro.ru`)
                - traefik.http.services.frontend.loadBalancer.server.port=80
                - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.app.rebit-pro.ru/(.*)$$
                - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}app.rebit-pro.ru/$${2}
                - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
                - traefik.http.routers.frontend.middlewares=frontend-redirect,secure-headers
                - traefik.http.routers.frontend.entryPoints=https
                - traefik.http.routers.frontend.tls=true
                - traefik.http.routers.frontend.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    api:
        image: ${REGISTRY}/rebit-p2p-api:${IMAGE_TAG}
        networks:
          - traefik-public
          - default
        volumes:
          - type: bind
            source: /srv/rebit-p2p/bitrix
            target: /app/public/bitrix
          - type: bind
            source: /srv/rebit-p2p/upload
            target: /app/public/upload
          - type: bind
            source: /srv/rebit-p2p/sessions
            target: /var/lib/php/sessions
        deploy:
          labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api.rule=Host(`api.rebit-pro.ru`)
            - traefik.http.services.api.loadBalancer.server.port=80
            - traefik.http.routers.api.middlewares=secure-headers
            - traefik.http.routers.api.entryPoints=https
            - traefik.http.routers.api.tls=true
            - traefik.http.routers.api.tls.certResolver=letsEncrypt
          mode: replicated
          replicas: 2
          update_config:
            parallelism: 1
            delay: 5s
            order: start-first  # Сначала запустить новый, затем остановить старый
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost/health" ]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 30s
          start_interval: 5s

    api-php-fpm:
        image: ${REGISTRY}/rebit-p2p-api-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
          APP_DEBUG: ${APP_DEBUG:-0}
          APP_ENV: ${APP_ENV:-production}
          BYBIT_TESTNET_BASE_URL: ${BYBIT_TESTNET_BASE_URL:-https://api-testnet.bybit.com}
          BYBIT_MAINNET_BASE_URL: ${BYBIT_MAINNET_BASE_URL:-https://api.bybit.com}
        volumes:
          - type: bind
            source: /srv/rebit-p2p/bitrix
            target: /app/public/bitrix
          - type: bind
            source: /srv/rebit-p2p/upload
            target: /app/public/upload
          - type: bind
            source: /srv/rebit-p2p/sessions
            target: /var/lib/php/sessions
        deploy:
          mode: replicated
          replicas: 2
          update_config:
            parallelism: 1
            delay: 5s
            order: start-first
        healthcheck:
          test: [ "CMD-SHELL", "php -v >/dev/null 2>&1" ] # Или свой скрипт
          interval: 10s
          timeout: 5s
          retries: 3

    api-mysql:
        image: percona:8.0
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - api-mysql:/var/lib/mysql
        deploy:
            placement:
                constraints: [ node.labels.db == db ]
            endpoint_mode: dnsrr

volumes:
    api-mysql:

networks:
    traefik-public:
        external: true
