import {
  mdiClose,
  mdiAccountCircle,
  mdiAccountCircleOutline,
  mdiCircle,
  mdiHome,
  mdiPlus,
  mdiEarth,
  mdiInstagram,
  mdiFacebook,
  mdiLinkedin,
  mdiAttachment,
  mdiLayersOutline,
  mdiThumbUpOutline,
  mdiMessageOutline,
  mdiReply,
  mdiMagnify,
  mdiAccountMultipleOutline,
  mdiAccountPlusOutline,
  mdiVideoOutline,
  mdiMessage,
  mdiBlockHelper,
  mdiTwitter,
  mdiAccountOutline,
  mdiEmailOutline,
  mdiInbox,
  mdiSendOutline,
  mdiNotebookOutline,
  mdiAlertOutline,
  mdiDeleteOutline,
  mdiStarOutline,
  mdiBookmarkOutline,
  mdiLabelOutline,
  mdiLabel,
  mdiStar,
  mdiForward,
  mdiPlusCircleOutline,
  mdiDomain,
  mdiBriefcaseOutline,
  mdiPhoneOutline,
  mdiCalendarOutline,
  mdiAlert,
  mdiAlertCircleOutline,
  mdiCartOutline,
  mdiCloseCircle,
  mdiEyeOff,
  mdiEye,
  mdiContentCopy,
  mdiCart,
  mdiMenuDown,
  mdiVideo,
  mdiAccountMultiple,
  mdiCheckboxMarkedCircleOutline,
  mdiMenuLeft,
  mdiMenuRight,
  mdiHeart,
  mdiHeartHalf,
  mdiHeartOutline,
  mdiCircleOutline,
  mdiFood,
  mdiLaptop,
  mdiSleep,
  mdiRepeat,
  mdiFormatAlignLeft,
  mdiFormatAlignCenter,
  mdiFormatAlignRight,
  mdiFormatAlignJustify,
  mdiFormatItalic,
  mdiFormatBold,
  mdiFormatUnderline,
  mdiFormatColorFill,
  mdiFormatColorText,
  mdiCheck,
  mdiCheckCircle,
  mdiPlay,
  mdiBasketball,
  mdiCircleHalf,
  mdiLanguageHtml5,
  mdiNodejs,
  mdiCodeJson,
  mdiLanguageMarkdown,
  mdiFilePdfBox,
  mdiFileImage,
  mdiFileDocumentOutline,
  mdiFileExcel,
  mdiFolder,
  mdiFolderOpen,
  mdiCloseCircleOutline,
  mdiFolderNetwork,
  mdiHomeVariant,
  mdiFileOutline,
  mdiRewind,
  mdiPause,
  mdiFastForward,
  mdiCamera,
  mdiSnowflake,
  mdiLeaf,
  mdiFire,
  mdiWater,
  mdiClock,
  mdiOpenInNew,
  mdiRefresh,
  mdiHorseVariantFast,
  mdiTire,
  mdiPencilOutline,
  mdiBookOutline,
  mdiBookMultipleOutline,
  mdiBackupRestore,
  mdiChevronUp,
  mdiChevronDown,
  mdiVideoInputComponent,
  mdiFileDocument,
  mdiFileUpload,
  mdiFile,
  mdiUpload,
  mdiCloudUpload,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCreditCardOutline,
  mdiCalendarBlank,
  mdiLockOutline,
  mdiPaperclip,
  mdiGithub,
  mdiAccount,
  mdiAlarm,
  mdiCakeVariant,
  mdiBeer,
  mdiGlassMug,
  mdiLiquor,
  mdiGlassMugVariant,
  mdiBookmarkMinus,
  mdiBookmark,
  mdiContentSave
} from '@mdi/js';

export const icons = {
  close: mdiClose,
  accountCircle: mdiAccountCircle,
  accountCircleOutline: mdiAccountCircleOutline,
  circle: mdiCircle,
  circleOutline: mdiCircleOutline,
  circleHalf: mdiCircleHalf,
  home: mdiHome,
  plus: mdiPlus,
  earth: mdiEarth,
  instagram: mdiInstagram,
  facebook: mdiFacebook,
  twitter: mdiTwitter,
  linkedin: mdiLinkedin,
  attachment: mdiAttachment,
  layerOutline: mdiLayersOutline,
  thumbUpOutline: mdiThumbUpOutline,
  messageOutline: mdiMessageOutline,
  reply: mdiReply,
  magnify: mdiMagnify,
  accountMultilineOutline: mdiAccountMultipleOutline,
  accountPlusOutline: mdiAccountPlusOutline,
  videoOutline: mdiVideoOutline,
  message: mdiMessage,
  blockHelper: mdiBlockHelper,
  accountOutline: mdiAccountOutline,
  emailOutline: mdiEmailOutline,
  inbox: mdiInbox,
  sendOutline: mdiSendOutline,
  notebookOutline: mdiNotebookOutline,
  alertOutline: mdiAlertOutline,
  deleteOutline: mdiDeleteOutline,
  starOutline: mdiStarOutline,
  star: mdiStar,
  bookmarkOutline: mdiBookmarkOutline,
  labelOutline: mdiLabelOutline,
  label: mdiLabel,
  forward: mdiForward,
  plusCircleOutline: mdiPlusCircleOutline,
  domain: mdiDomain,
  briefcaseOutline: mdiBriefcaseOutline,
  phoneOutline: mdiPhoneOutline,
  calendarOutline: mdiCalendarOutline,
  alert: mdiAlert,
  alertCircleOutline: mdiAlertCircleOutline,
  cartOutline: mdiCartOutline,
  cart: mdiCart,
  closeCircle: mdiCloseCircle,
  eyeOff: mdiEyeOff,
  eye: mdiEye,
  contentCopy: mdiContentCopy,
  menuDown: mdiMenuDown,
  video: mdiVideo,
  accountMultiple: mdiAccountMultiple,
  checkboxMarkedCircleOutline: mdiCheckboxMarkedCircleOutline,
  menuLeft: mdiMenuLeft,
  menuRight: mdiMenuRight,
  heart: mdiHeart,
  heartHalf: mdiHeartHalf,
  heartOutline: mdiHeartOutline,
  food: mdiFood,
  laptop: mdiLaptop,
  sleep: mdiSleep,
  repeat: mdiRepeat,
  formatAlignLeft: mdiFormatAlignLeft,
  formatAlignCenter: mdiFormatAlignCenter,
  formatAlignRight: mdiFormatAlignRight,
  formatAlignJustify: mdiFormatAlignJustify,
  formatItalic: mdiFormatItalic,
  formatBold: mdiFormatBold,
  formatUnderline: mdiFormatUnderline,
  formatColorFill: mdiFormatColorFill,
  formatColorText: mdiFormatColorText,
  check: mdiCheck,
  checkCircle: mdiCheckCircle,
  play: mdiPlay,
  basketball: mdiBasketball,
  languagehtml5: mdiLanguageHtml5,
  nodejs: mdiNodejs,
  codejson: mdiCodeJson,
  languagemarkdown: mdiLanguageMarkdown,
  filepdf: mdiFilePdfBox,
  fileimage: mdiFileImage,
  filedocumentoutline: mdiFileDocumentOutline,
  filexcel: mdiFileExcel,
  folder: mdiFolder,
  folderopen: mdiFolderOpen,
  closecircleoutline: mdiCloseCircleOutline,
  foldernetwork: mdiFolderNetwork,
  homevariant: mdiHomeVariant,
  fileoutline: mdiFileOutline,
  rewind: mdiRewind,
  pause: mdiPause,
  fastforward: mdiFastForward,
  camera: mdiCamera,
  snowflake: mdiSnowflake,
  leaf: mdiLeaf,
  fire: mdiFire,
  water: mdiWater,
  clock: mdiClock,
  openInNew: mdiOpenInNew,
  refresh: mdiRefresh,
  horseVariantFast: mdiHorseVariantFast,
  tire: mdiTire,
  pencilOutline: mdiPencilOutline,
  bookOutline: mdiBookOutline,
  bookMultipleOutline: mdiBookMultipleOutline,
  backupRestore: mdiBackupRestore,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  videoInputComponent: mdiVideoInputComponent,
  fileDocument: mdiFileDocument,
  fileUpload: mdiFileUpload,
  file: mdiFile,
  upload: mdiUpload,
  cloudUpload: mdiCloudUpload,
  creditCardOutline: mdiCreditCardOutline,
  calendarBlank: mdiCalendarBlank,
  lockOutline: mdiLockOutline,
  paperClip: mdiPaperclip,
  github: mdiGithub,
  account: mdiAccount,
  alarm: mdiAlarm,
  cakeVariant: mdiCakeVariant,
  beer: mdiBeer,
  glassMug: mdiGlassMug,
  liquor: mdiLiquor,
  glassMugVariant: mdiGlassMugVariant,
  bookmarkMinus: mdiBookmarkMinus,
  bookmark: mdiBookmark,
  contentSave: mdiContentSave
};
