site:
	ansible-playbook -i hosts.yml site.yml -vv
	
renew-certificates:
	ansible-playbook -i hosts.yml renew-certificates.yml

authorize:
	ansible-playbook -i hosts.yml authorize.yml

docker-login:
	ansible-playbook -i hosts.yml renew-certificates.yml