path: ./public/local
jobs: 10
cache: var/phplint.json
extensions:
  - php
exclude:
  - vendor
  - public/bitrix
  - public/local/modules/rebit.photoorder/orm_annotations.php
  - public/local/modules/rebit.photoorder/install/index.php