name: 🛠️ Build, Test & 🚀 Deploy to Swarm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.TOKEN_GIT_HUB }}

      - name: 🏗️ Build images
        run: |
          export REGISTRY="${{ secrets.REGISTRY }}"
          export IMAGE_TAG="${GITHUB_SHA::8}"
          export BUILD_NUMBER="${GITHUB_RUN_NUMBER}"
          make build

      - name: 📤 Push images
        run: |
          export REGISTRY="${{ secrets.REGISTRY }}"
          export IMAGE_TAG="${GITHUB_SHA::8}"
          export BUILD_NUMBER="${GITHUB_RUN_NUMBER}"
          make push

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-push
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: 🔑 Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.PORT }}" "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy via make
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          IMAGE_TAG: ${{ github.sha }} # или лучше: ${{ github.sha[0:8] }} чтобы совпадало с build/push
          BUILD_NUMBER: ${{ github.run_number }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          TOKEN_GIT_HUB: ${{ secrets.TOKEN_GIT_HUB }}
        run: |
          make deploy